name: ci

env:
  NETCORE_VERSION: 6.0.100
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOTNET_ROLL_FORWARD: Major

on:
  push:
    branches:
    - main
    - feature/*
    - release/*
    paths:
      - ".github/workflows/**"
      - "build/**"
      - "hive.core/**"
      - "hive.microservices/**"
      - "hive.logging/**"
      - "GitVersion.yml"
  pull_request:
    types:
    - closed
    branches:
    - main
    paths:
      - ".github/workflows/**"
      - "build/**"
      - "hive.core/**"
      - "hive.microservices/**"
      - "hive.logging/**"
      - "GitVersion.yml"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    uses: ionizd/hive/.github/workflows/nuke.yml@main
    name: build
    with:
      Directory: ${{ github.workspace }}
      NetCoreVersion: 6.0.100
      Compile:      true
      UnitTests:    true
      Pack:         true
      Push:         true
      NuGetApiUrl:  'https://api.nuget.org/v3/index.json'
    secrets:
      NuGetFeedCloudTek:  ${{ secrets.NUGET_FEED_CLOUDTEK }}
      NuGetApiKey:        ${{ secrets.NUGET_API_KEY }}
      NuGetUsername:      ${{ secrets.NUGET_USERNAME }}
      NuGetPassword:      ${{ secrets.NUGET_PASSWORD }}
