name: ci

env:
  NETCORE_VERSION: 8.0.201
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOTNET_ROLL_FORWARD: Major

on:
  push:
    branches:
    - main
    - feature/*
    - release/*
    - bug/*
    paths:
      - ".github/workflows/**"
      - "build/**"
      - "hive.core/**"
      - "hive.microservices/**"
      - "hive.logging/**"
      - "GitVersion.yml"
  pull_request:
    types:
    - closed
    branches:
    - main
    paths:
      - ".github/workflows/**"
      - "./config/dotnet-tools.json"
      - "build/**"
      - "hive.core/**"
      - "hive.microservices/**"
      - "hive.logging/**"
      - "GitVersion.yml"
      - "global.json"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    uses: ./.github/workflows/nuke.yml
    name: build
    with:
      Directory: ${{ github.workspace }}
      NetCoreVersion: 8.0.201
      Compile:      true
      UnitTests:    true
      Pack:         true
      Push:         true
      NuGetApiUrl:  'https://api.nuget.org/v3/index.json'
    secrets:
      NuGetFeedCloudTek:  ${{ secrets.NUGET_FEED }}
      NuGetApiKey:        ${{ secrets.NUGET_API_KEY_HIVE }}
      NuGetUsername:      ${{ secrets.NUGET_USERNAME }}
      NuGetPassword:      ${{ secrets.NUGET_PASSWORD }}
